"""empty message

Revision ID: 7f0bc502182d
Revises: a36951f9a04a
Create Date: 2020-04-24 17:07:02.141169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0bc502182d'
down_revision = 'a36951f9a04a'
branch_labels = None
depends_on = None



def drop_column_sqlite(tablename, columns):
    """ column dropping functionality for SQLite """
 
    # we need copy to make a deep copy of the column attributes
    from copy import copy
 
    # get the db engine and reflect database tables
    engine = op.get_bind()
    meta = sa.MetaData(bind=engine)
    meta.reflect()
 
    # create a select statement from the old table
    old_table = meta.tables[tablename]
    select = sa.sql.select([c for c in old_table.c if c.name not in columns])
 
    # get remaining columns without table attribute attached
    remaining_columns = [copy(c) for c in old_table.columns
            if c.name not in columns]
    for column in remaining_columns:
        column.table = None
 
    # create a temporary new table
    new_tablename = '{0}_new'.format(tablename)
    op.create_table(new_tablename, *remaining_columns)
    meta.reflect()
    new_table = meta.tables[new_tablename]
 
    # copy data from old table
    insert = sa.sql.insert(new_table).from_select(
            [c.name for c in remaining_columns], select)
    engine.execute(insert)
 
    # drop the old table and rename the new table to take the old tables
    # position
    op.drop_table(tablename)
    op.rename_table(new_tablename, tablename)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_column_sqlite('query_text_parameters', 'parameter_nullable')
    drop_column_sqlite('query_text_parameters', 'parameter_python_var')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_text_parameters', sa.Column('parameter_python_var', sa.VARCHAR(length=100), nullable=False))
    op.add_column('query_text_parameters', sa.Column('parameter_nullable', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###
