"""empty message

Revision ID: b54ef033082a
Revises: 7f0bc502182d
Create Date: 2020-04-24 18:46:34.359111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54ef033082a'
down_revision = '7f0bc502182d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'query_text_parameters', 'query', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_text_parameters', type_='foreignkey')
    # ### end Alembic commands ###
