"""empty message

Revision ID: ccd651371d0e
Revises: c46c22aa1a18
Create Date: 2020-04-26 17:44:52.695103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd651371d0e'
down_revision = 'c46c22aa1a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_marked_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_marked_query')
    # ### end Alembic commands ###
